### PR TITLE
feat: Hijack a Session Lesson

### LINKED ISSUE #602: Lessons on session management flaws and weak session IDs
What happened to the session management flaws that were available in WebGoat 7? I can't find them in WebGoat 8? Are they just being added in slowly or am I missing something? I tried searching through release notes to see if the change was mentioned but could not find anything.

### PR DESCRIPTION
**Pull request by aolle**
New Hijack a Session Lesson.

Fixes #602

### CODE REVIEW

**Comment by nbaars** [comment]
@aolle can we merge this one?

**Comment by aolle** [comment]
Hi @nbaars, not yet please, some tests remaining actually. I've plans to finish the lesson by this week, then I will squash and let you know for review.

**Comment by aolle** [comment]
@nbaars ready for review!

**Comment by nbaars** [comment]
@aolle super! I cherry-picked your commits there was a conflict making the rebase not possible. Closing the PR

**Pull request closed without merging**
