### PR TITLE
Add coverage profile

### PR DESCRIPTION
**Pull request by aolle**
I added a independent optional profile for running the coverage report. It may be interesting if we want to know our code coverage.
It can be executed with:
`mvn verify -Pcoverage`
The report is available in the `target/site` directory.
I tested all on my side and it's working, but @nbaars , @zubcevic  , please, one of you, as I added a little change in the surefire plugin, please can you take a look and check that it's also working on your side?

Thanks!

### CODE REVIEW

**Comment by zubcevic** [comment]
I will have a look this week, but already sounds useful

**Comment by nbaars** [comment]
I've tried, but I see:

```java
[INFO] --- jacoco-maven-plugin:0.8.8:check (check) @ webgoat ---
[INFO] Skipping JaCoCo execution due to missing execution data file:/Users/nbaars/workspace/WebGoat/target/jacoco.exec
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.8:report (default-report) @ webgoat ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
```
and no file in `target/site`

**Comment by aolle** [comment]
@nbaars sorry, my fault. Please, can you try again?

**Comment by aolle** [comment]
@nbaars Nice! Glad to know that it's working. I will check the integration tests part, as I added the pre-integration-test phase.
The idea behind this is work to maximize the current code coverage to be aware if any future change break something.
Marked as draft for now, I will review that part and merge it when ready.
Thank you!

**Comment by aolle** [comment]
@nbaars 
If you agree, I'm going to merge this PR with only the unit test part for the following reason:

I've been looking into the integration test part because Jacoco is generating empty reports for it. After debugging the involved Maven plugins, I've concluded that the process-exec-maven-plugin we use to start the WebGoat instance isn't managing the MOJO processes in the way that Jacoco expects. As a result, the resulting report is null.

Upon further investigation, it appears that the instance is handling the process in a way that returns an error code. I've noticed that it invokes 'destroy', which seems to return an error code depending on the implementation. However, ultimately this approach doesn't meet the needs of the agent.

Furthermore, I'd like to emphasize that during the integration tests, I haven't seen a clear log of the running instance, and it seems that processLogFile isn't working correctly either. While running these tests, I've noticed some stack traces during execution. Although they don't cause the test to fail, I think it would be a good idea to review them. 

Additionally, there's something else that's not working correctly with the plugin in general: the information doesn't seem to be reflected correctly, as we can see:

```
[INFO] Stopping process: null
[INFO] Stopped process: null
```

Furthermore, it appears that they're not accepting PRs in the project.

There's a very simple way to confirm this: manually start the WebGoat instance during integration tests instead of using the plugin. For example:

`java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=localhost:8000,suspend=n -jar --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED -Dspring.main.banner-mode=off -Dspring.datasource.url=jdbc:hsqldb:file:/tmp/webgoat -javaagent:$HOME/.m2/repository/org/jacoco/org.jacoco.agent/0.8.8/org.jacoco.agent-0.8.8-runtime.jar=destfile=/tmp/jacoco-it.exec /tmp/webgoat-2023.4-SNAPSHOT.jar`

After running the tests, we can manually generate the report using jacoco-cli:

`java -jar org.jacoco.cli-0.8.8-nodeps.jar report jacoco-it.exec --html ./report --classfiles $HOME/WebGoat/target/classes/`

It works, we will see:

it

Obviously, it cannot be confused with the coverage of unit tests, which has the following current coverage:

ut

Note: to cover the integration tests, we need to add all the necessary parts to the pom.xml that are not included in this PR. If you run the reproducer with the current PR, the result of the integration tests will not be generated.

Given this, I think we should consider whether we're comfortable with the current situation, or if we should concentrate our efforts on enhancing integration tests with an alternative approach.

In the meantime, I will work on improving the coverage of the unit test part.
For now, the execution will be instead:

`mvn test -Pcoverage`

Please let me know your thoughts.

**Comment by nbaars** [comment]
> Furthermore, I'd like to emphasize that during the integration tests, I haven't seen a clear log of the running instance, and it seems that processLogFile isn't working correctly either. 

This might be because we explicitly turn off logging. Back in the days when we were using Travis CI we failed to build the project due to too much logging.

Let's have coverage like this first later on we can add integration tests. At first we have work to be done in the unit tests to get the coverage higher 😄

**Review by nbaars — APPROVED** [review]

**Comment by aolle** [comment]
Great!

**Pull request merged**
