### PR TITLE
How to create a Legacy Lesson - instruction edit #177

### PR DESCRIPTION
**Pull request by b1rd0fb3auty14**
Changes to make build pass as it was failing due to missed parenthesis. To ultimately fix the below issues:
1. Update the user guide to point to the wiki.
2. Add the slack channel
3. Change the feedback email to point to the group mailing list.

### CODE REVIEW

**Comment by nbaars** [comment]
@b1rd0fb3auty14 can you please sign the CLA? You seem so use '=' as a git user?

**Comment by b1rd0fb3auty14** [comment]
@nbaars - I will sign the CLA.

**Comment by b1rd0fb3auty14** [comment]
@nbaars - Will I need to revert my changes to include my username? I tried contacting github with the issue and they stated that the only way that I can change this is by the following: 
"Hello,

The only way to resolve this is to rewrite the git history and replace all of the email addresses for every commit.

https://help.github.com/articles/changing-author-info/

We do not recommend doing this though except to remove sensitive information, as a mistake can permanently damage your repository.

If other people are working on that project at the same time, you will have to ask them to stop pushing changes until you are done.

When you are done they will have to clone a fresh copy or rebase all branches you will have touched."

Can you provide a more non-evasive way for me to do the change so I can complete the CLA?

**Comment by nbaars** [comment]
@b1rd0fb3auty14 ah I see, well I will just merge it manually.

**Comment by b1rd0fb3auty14** [comment]
@nbaars - Sorry, and thanks! I think I have configured my email now, so hopefully I will not have this problem again.

**Comment by nbaars** [comment]
Merged manually

**Pull request closed without merging**
