### PR TITLE
Fix: Update state of software supply chain links

### PR DESCRIPTION
**Pull request by maurycupitt**
Updating the state of the software supply chain links in the Vulnerable Components section.

### CODE REVIEW

**Comment by zubcevic** [comment]
it looks fine and thank you for the update. I have to check why the ui test all of a sudden fails.

**Comment by aolle** [comment]
@maurycupitt it should be good if you can squash the commits into one.

**Comment by zubcevic** [comment]
same test did work on last commit https://github.com/WebGoat/WebGoat/actions/runs/6866139261/job/18671706970?pr=1658

**Comment by zubcevic** [comment]
If you merge/rebase from the latest changes on the main branch, you should pass the UI test.

**Comment by zubcevic** [comment]
This has been merged

**Pull request closed without merging**
