### PR TITLE
Iaas seed

### PR DESCRIPTION
**Pull request by nparks-owasp**
Good Day,

The initial seeding PR for adding IaaS Quickstarts!

The initial fragments are
- AWS Pipeline for Building using AWS (deploying next)
- Deploying the Latest WebGoat 8 Container Image to GKE

@nbaars , It is way easier to deploy the WebGoat 8 image to GKE so I made sure that was in better condition and just removed the ECR/ECS from this initial seeding PR

There are no code changes, just additions for the QuickStarts

### CODE REVIEW

**Comment by misfir3** [comment]
sorry for no response so far. Will look at this soon. Thanks for throwing in!

**Comment by nparks-owasp** [comment]
no problem @misfir3  I just noticed an incorrect sequence in the GKE-Docker steps. I will fix that this weekend.

**Comment by nparks-owasp** [comment]
@misfir3 much better

**Comment by nbaars** [comment]
@nparks-owasp looks great, merged the pull request thanks!

**Pull request merged**
